scrape_configs:
  - job_name: "nodejs_app"
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"]
